/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.47
 * Generated at: 2018-07-22 18:20:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import webProject.bean.*;
import webProject.daoImpl.*;
import webProject.service.*;
import java.util.*;

public final class AdvertiseRole_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("webProject.service");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("webProject.bean");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("webProject.daoImpl");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--Final project-->\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    \r\n");
      out.write("    <title>Homeless Final Project</title>\r\n");
      out.write("    \r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("\t\t<script src=\"http://html5shiv.googlecode.com/svn/trunk/html5.js\"></script>\r\n");
      out.write("\t\t<![endif]-->\r\n");
      out.write("        <!--[if lte IE 9]> \r\n");
      out.write("\t    <script src=\"http://css3-mediaqueries-\tjs.googlecode.com/svn/trunk/css3-\tmediaqueries.js\"></script> \r\n");
      out.write("        <![endif]-->\r\n");
      out.write("         \r\n");
      out.write("    <link rel =\"stylesheet\" href=\"CSS/homeless.css\" type=\"text/css\">\r\n");
      out.write("     <link rel =\"stylesheet\" href=\"CSS/style.css\" type=\"text/css\">\r\n");
      out.write("     <link rel =\"stylesheet\" href=\"CSS/servicesStyle.css\" type=\"text/css\">\r\n");
      out.write("    \r\n");
      out.write("   <meta name=\"keywords\" content=\"homeless, welfare, charity, volunteer, homelessness\">\r\n");
      out.write("  <script>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("    function access(){ \r\n");
      out.write("        \t");
         	
              if(request.getSession().getAttribute("msg")!=null){
      
            String str=request.getSession().getAttribute("msg").toString();
      out.write("           \r\n");
      out.write("            alert('notice'+\" : \"+\"");
      out.print(str);
      out.write("\");\r\n");
      out.write("            ");
  
             request.getSession().setAttribute("msg", null); }else {
      out.write("\r\n");
      out.write("          \r\n");
      out.write("            ");
}
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("    \r\n");
      out.write("    function changeVal() \r\n");
      out.write("    { \r\n");
      out.write(" \t  \r\n");
      out.write(" \t  var organisationName=document.forms[\"form\"][\"organisationName\"].value;\r\n");
      out.write(" \t  window.location.replace(\"AdvertiseRole.jsp?organisationName=\"+organisationName);\r\n");
      out.write(" \t     \r\n");
      out.write(" \t   \r\n");
      out.write("    } \r\n");
      out.write("    </script>\r\n");
      out.write(" </head>\r\n");
      out.write("<body onload=\"access()\">\r\n");
      out.write("    \r\n");
      out.write("       <header class=\"mainpic\">\r\n");
      out.write("          \r\n");
      out.write("           <div class = \"welcome\">\r\n");
      out.write("               <h1>Post a Volunteering Opportunity</h1><br/>\r\n");
      out.write("               <font color=\"white\"><h2>I-VOL is the national searchable database of volunteering opportunities in Ireland and is owned, managed and administered by Volunteer Ireland, the network of Volunteer Centres and Volunteer Information Services in Ireland .\r\n");
      out.write("\t\t\tIn order to register your volunteering opportunity/ies with us, your organisation must be already registered on I-VOL. Click here if you are not already registered. In order to proceed, you will need your key/password that was provided to you on your initial registration. If you do not know this, you can use the retrieve key function.</h2></font>\r\n");
      out.write("              \r\n");
      out.write("               </div>\r\n");
      out.write("         </header>\r\n");
      out.write("                <div class=\"box\" style=\"background:#808080; color:black; text-color:black;padding-left:15px;margin-left:300px;float:left;width:50% ; height:50%;margin-right:25px;margin-top:25px;margin-bottom:100px;\"> \r\n");
      out.write("               \t<form action=\"advertiseRoleServlet\" method=\"post\" id=\"form\">\r\n");
      out.write("               \t\r\n");
      out.write("      \t\t\t\t<h1>Advertise a role</h1>\r\n");
      out.write("      \t\t\t\t<table>\r\n");
      out.write("      \t\t\t\t<tr>\r\n");
      out.write("      \t\t\t\t\t<td>Organization Name:</td>\r\n");
      out.write("      \t\t\t\t\t<td>\r\n");
      out.write("      \t\t\t\t\t<select name=\"organisationName\" style=\"margin-left:40px;width:340px;\" id=\"organisationName\" onchange=\"changeVal()\">\r\n");
      out.write("      \t\t\t\t\t");

      					AbstractDao abd=new AbstractDao();
      					List<DataInterface> ls=abd.listByQuery("from AddOrganisationBean");
      					Iterator<DataInterface> it=ls.iterator();
      					while(it.hasNext())
      					{
      						AddOrganisationBean org=(AddOrganisationBean)it.next();
      					
      					
      					
      out.write("\r\n");
      out.write("      \t\t\t\t\t<option value=\"");
      out.print(org.getOrganisationName() );
      out.write('"');
      out.write('>');
      out.print(org.getOrganisationName() );
      out.write("</option>\r\n");
      out.write("      \t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("      \t\t\t\t\t</select>\r\n");
      out.write("      \t\t\t\t\t</td>\r\n");
      out.write("      \t\t\t\t</tr>\r\n");
      out.write("      \t\t\t\t");

      				String organisationName=request.getParameter("organisationName");
      				System.out.println("organnn"+organisationName);
      				if(organisationName==null)
      					{
      out.write("\r\n");
      out.write("      \t\t\t\t\t<tr>\r\n");
      out.write("      \t\t\t\t\t<td>Organization Key/Access Code:</td>\r\n");
      out.write("      \t\t\t\t\t<td>\r\n");
      out.write("      \t\t\t\t\t\r\n");
      out.write("      \t\t\t\t\t<input type=\"text\"  name=\"key\" placeholder=\"Enter Key\" required/></td>\r\n");
      out.write("      \t\t\t\t\t\r\n");
      out.write("      \t\t\t\t</tr>\r\n");
      out.write("      \t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("      \t\t\t\t<tr>\r\n");
      out.write("      \t\t\t\t\t<td>Organization Key/Access Code:</td>\r\n");
      out.write("      \t\t\t\t\t<td>\r\n");
      out.write("      \t\t\t\t\t");

      					
      					List<DataInterface> lst=new AbstractDao().listByQuery("from AddOrganisationBean where organisationName="+"'"+organisationName+"'");
      					Iterator<DataInterface>itr=lst.iterator();
      					while(itr.hasNext())
      					{
      						AddOrganisationBean org=(AddOrganisationBean)itr.next();
      					
      					
      out.write("\r\n");
      out.write("      \t\t\t\t\t<input type=\"text\"  name=\"key\" value=\"");
      out.print(org.getKey() );
      out.write("\" readonly required/></td>\r\n");
      out.write("      \t\t\t\t\t");
}} 
      out.write("\r\n");
      out.write("      \t\t\t\t</tr>\r\n");
      out.write("      \t\t\t\t<tr>\r\n");
      out.write("      \t\t\t\t\t<td>Enter Location:</td>\r\n");
      out.write("      \t\t\t\t\t<td><input type=\"text\" placeholder=\"Enter Location\" name=\"location\" required/></td>\r\n");
      out.write("      \t\t\t\t</tr>\t\r\n");
      out.write("      \t\t\t\t<tr>\r\n");
      out.write("      \t\t\t\t\t<td>Enter Role:</td>\r\n");
      out.write("      \t\t\t\t\t<td><input type=\"text\" placeholder=\"Enter Role\" name=\"role\" required/></td>\r\n");
      out.write("      \t\t\t\t</tr>\t\r\n");
      out.write("      \t\t\t\t<tr>\r\n");
      out.write("      \t\t\t\t\t<td>Select Number of volunteers Required:</td>\r\n");
      out.write("      \t\t\t\t\t<td>\r\n");
      out.write("      \t\t\t\t\t\t<select name=\"NoOfVolunteer\" style=\"margin-left:40px;width:340px;\">\r\n");
      out.write("      \t\t\t\t\t\t\t<option value=\"1\">1</option>\r\n");
      out.write("      \t\t\t\t\t\t\t<option value=\"2\">2</option>\r\n");
      out.write("      \t\t\t\t\t\t\t<option value=\"3\">3</option>\r\n");
      out.write("      \t\t\t\t\t\t\t<option value=\"4\">4</option>\r\n");
      out.write("      \t\t\t\t\t\t\t<option value=\"5\">5</option>\r\n");
      out.write("      \t\t\t\t\t\t\t<option value=\"6\">6</option>\r\n");
      out.write("      \t\t\t\t\t\t\t<option value=\"7\">7</option>\r\n");
      out.write("      \t\t\t\t\t\t\t<option value=\"8\">8</option>\r\n");
      out.write("      \t\t\t\t\t\t\t<option value=\"9\">9</option>\r\n");
      out.write("      \t\t\t\t\t\t\t<option value=\"10\">10</option>\r\n");
      out.write("      \t\t\t\t\t\t\t<option value=\"15\">15</option>\r\n");
      out.write("      \t\t\t\t\t\t\t<option value=\"20\">20</option>\r\n");
      out.write("      \t\t\t\t\t\t\t<option value=\"50\">50</option>\r\n");
      out.write("      \t\t\t\t\t\t\t<option value=\"100\">100</option>\r\n");
      out.write("      \t\t\t\t\t\t\t<option value=\"200\">200</option>\r\n");
      out.write("      \t\t\t\t\t\t\t<option value=\"500\">500</option>\r\n");
      out.write("      \t\t\t\t\t\t\t<option value=\"1000\">1000</option>\r\n");
      out.write("      \t\t\t\t\t\t</select>\r\n");
      out.write("      \t\t\t\t\t\t</td>\r\n");
      out.write("      \t\t\t\t\t\t<td></td>\r\n");
      out.write("      \t\t\t\t\t</tr>\r\n");
      out.write("      \t\t\t\t\t<tr>\r\n");
      out.write("      \t\t\t\t\t\t<td>Select Skill required for this role:</td>\r\n");
      out.write("      \t\t\t\t\t\t<td><textarea name=\"skill\" placeholder=\"Enter text here..\" style=\"margin-left:40px;width:320px;\"></textarea></td>\r\n");
      out.write("      \t\t\t\t\t\t<td></td>\r\n");
      out.write("      \t\t\t\t\t</tr>\r\n");
      out.write("      \t\t\t\t\t<tr>\r\n");
      out.write("        \t\t\t\t\t<td><button type=\"submit\" style=\"width:200px;\">Submit</button></td>\r\n");
      out.write("        \t\t\t\t\t<td><button type=\"reset\" style=\"width:200px;\">Cancel</button></td>\r\n");
      out.write("        \t\t\t\t</tr>\r\n");
      out.write("      \t\t\t\t\t\r\n");
      out.write("  \t\t\t\t    </table>   \r\n");
      out.write("  \t\t\t\t    \r\n");
      out.write("  \t\t\t\t    <center><a href=\"login.jsp\" class=\"btn buttonTwo\">Login</a></center>       \t\r\n");
      out.write("               \t</form><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>\r\n");
      out.write("               \r\n");
      out.write("                </div><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>        <section id=\"footer\">\r\n");
      out.write("           <h3>footer of the website </h3>\r\n");
      out.write("       </section>\r\n");
      out.write("       \r\n");
      out.write("   </body>\r\n");
      out.write("  </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
