/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.47
 * Generated at: 2018-07-22 18:24:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import webProject.bean.*;
import webProject.daoImpl.*;
import webProject.service.*;

public final class contactus_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("webProject.service");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("webProject.bean");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("webProject.daoImpl");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!--Web design-->\n");
      out.write("\n");
      out.write("<!--Final project-->\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("    <head>\n");
      out.write("\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    \n");
      out.write("    <title>Homeless Final Project</title>\n");
      out.write("    \n");
      out.write("    <!--[if lt IE 9]>\n");
      out.write("\t\t<script src=\"http://html5shiv.googlecode.com/svn/trunk/html5.js\"></script>\n");
      out.write("\t\t<![endif]-->\n");
      out.write("        <!--[if lte IE 9]> \n");
      out.write("\t    <script src=\"http://css3-mediaqueries-\tjs.googlecode.com/svn/trunk/css3-\tmediaqueries.js\"></script> \n");
      out.write("        <![endif]-->\n");
      out.write("         \n");
      out.write("    <link rel =\"stylesheet\" href=\"CSS/homeless.css\" type=\"text/css\">\n");
      out.write("    <link rel =\"stylesheet\" href=\"CSS/style.css\" type=\"text/css\">\n");
      out.write("    <link rel =\"stylesheet\" href=\"CSS/servicesStyle.css\" type=\"text/css\">\n");
      out.write("    <meta name=\"keywords\" content=\"homeless, welfare, charity, volunteer, homelessness\">\n");
      out.write("     <script>\n");
      out.write("   \n");
      out.write("    function preventBack(){window.history.forward();}\n");
      out.write("   \tsetTimeout(\"preventBack()\", 0);\n");
      out.write("    window.onunload=function(){null};\n");
      out.write(" \n");
      out.write("    function access(){ \n");
      out.write("        \t");
 
        		
        	
              if(request.getSession().getAttribute("msg")!=null){
      
            String str=request.getSession().getAttribute("msg").toString();
      out.write("           \n");
      out.write("            alert('notice'+\" : \"+\"");
      out.print(str);
      out.write("\");\n");
      out.write("            ");
  
             request.getSession().setAttribute("msg", null); }else {
      out.write("\n");
      out.write("         \n");
      out.write("            ");
}
      out.write("\n");
      out.write("            } \n");
      out.write("        </script>\n");
      out.write("    </head>\n");
      out.write("    \n");
      out.write("   <body onload=\"access()\" background=\"images/Homeless.jpg\" >\n");
      out.write("   ");
  try{
	   StartVolunteeringBean user = (StartVolunteeringBean)request.getSession().getAttribute("user");
        AbstractDao abd=new AbstractDao();
     
       System.out.println("user"+user);
       if(user!=null)
       {
       
       
      out.write("\n");
      out.write("       <header>\n");
      out.write("     <nav>\n");
      out.write("           <a href=\"home.jsp\">Home</a>\n");
      out.write("\t\t\t<a href=\"aboutus.jsp\">About Us</a>\n");
      out.write("           <a href=\"volunteers.jsp\">Volunteers</a>\n");
      out.write("           <a href=\"organisations.jsp\">Organisations</a>\n");
      out.write("           <a href=\"resources.jsp\">Resources</a>\n");
      out.write("           <a href=\"contactus.jsp\">Contact us</a>\n");
      out.write("           <a href=\"logoutServlet\">LogOut</a>\n");
      out.write("       </nav>    \n");
      out.write("           </header>    \n");
      out.write("        \n");
      out.write("        \n");
      out.write("        <br/><br/>\n");
      out.write("       \n");
      out.write("        \n");
      out.write("            <div style=\"background:#808080;margin:25px;padding:20px;float:center;font-size:10px;\"> \n");
      out.write("        <div id=\"contactUsContent\">\n");
      out.write("            \n");
      out.write("            \n");
      out.write("                <h1>CONTACT US</h1><br/>\n");
      out.write("                \n");
      out.write("                <p>Click here to enroll in our dog walking services.Click here to enroll in our petsitting or hangout services. Click here to enroll in our Lil Bow Wow Doggy Care training package.</p> \n");
      out.write("                    <br/>\n");
      out.write("                <p>With a list of references and glowing customer reviews we pride ourselves on our quality customer service and the high level of attention and care we give our furry friends.</p>\n");
      out.write("                <br/>\n");
      out.write("                <p>Pooch Pals pet care is a fully bonded & insured member of Pet Sitters International.</p>\n");
      out.write("              </div>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"box\" style=\"background:#808080; color:black; text-color:black;padding-left:15px;margin-left:300px;float:left;width:50% ; height:55%;margin-right:25px;margin-top:25px;margin-bottom:25px;\"> \n");
      out.write("        <!--table for form on contact us page, what do you think about it??-->\n");
      out.write("        <h2>Fill in the form Below:</h2>\n");
      out.write("        <form action=\"contactUsServlet\" method=\"post\">\n");
      out.write("        <table>\n");
      out.write("        <tr>\n");
      out.write("        \t<td> Name:</td>\n");
      out.write("        \t<td style=\"width:200px;\"><input type=\"text\" name=\"name\"></td>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("        \t<td> Address:</td>\n");
      out.write("        \t<td><input type=\"text\" name=\"address\"> </td>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("        \t<td>E-mail:</td>\n");
      out.write("        \t<td> <input type=\"email\" id=\"email\" name=\"email\"> </td>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("        \t<td>Date of Birth:</td>\n");
      out.write("        \t<td><input type=\"text\" id=\"dob\" placeholder=\"DD/MM/YY\" name=\"dob\"></td>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("        \t<td>Gender of Dog:</td>\n");
      out.write("        \t<td>&nbsp;&nbsp;<input type=\"radio\" name=\"gender\" value=\"Male\" style=\"width:50px;\">Male&nbsp;&nbsp;&nbsp;&nbsp;<input type=\"radio\" name=\"gender\" value=\"Female\" style=\"width:50px;\">Female</td>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("        \t<td>Choose your service</td>\n");
      out.write("        \t<td><select name=\"intrest\">\n");
      out.write("        \t\t\t\t<option value=\"--Select Service--\">--Select Service--</option>\n");
      out.write("                        <option value=\"Computer Course\">Dog Walking</option>\n");
      out.write("                        <option value=\"Business Course\">Dog Grooming</option>\n");
      out.write("                        <option value=\"Art Course\">Over Night Stay</option>\n");
      out.write("                        <option value=\"Language Course\">Dog Obedience Training Course</option>\n");
      out.write("            </select></td>\n");
      out.write("         </tr>\n");
      out.write("         <tr>\n");
      out.write("         \t<td>Further Comment:</td>\n");
      out.write("         \t<td><textarea rows=\"4\" cols=\"50\" name=\"comment\" placeholder=\"Enter Text here...\"></textarea></td>\n");
      out.write("         </tr>\n");
      out.write("        <tr>\n");
      out.write("        \t<td><button type=\"submit\" style=\"width:200px;\">Submit</button></td>\n");
      out.write("        \t<td><button type=\"reset\" style=\"width:200px;\">Cancel</button></td>\n");
      out.write("        </tr>\n");
      out.write("        \n");
      out.write("        </table>\n");
      out.write("         </form>\n");
      out.write("        <!--embedded google map-->\n");
      out.write("        <iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2375.3656511564795!2d-6.204923048758653!3d53.46192497990524!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4867109152ecb1c3%3A0x2cf219f681eacf62!2sDublin+Dog+Training!5e0!3m2!1sen!2suk!4v1490696174731\" width=\"600\" height=\"450\" frameborder=\"0\" style=\"border:0\" allowfullscreen></iframe><br/><br/><br/><br/>\n");
      out.write("   \n");
      out.write("        </div><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>\n");
      out.write("        \t\t ");

       }
       else
       {
    	   response.sendRedirect("login.jsp");
       }
}catch(Exception e){
	String ipAddress = request.getHeader("X-FORWARDED-FOR");
	if (ipAddress == null) {
		   ipAddress = request.getRemoteAddr();
	}
	new controller().addLog("URLInjection", ipAddress);
	session.setAttribute("msg", "URLInjection detected");
	response.sendRedirect("login.jsp");
}

      out.write("\n");
      out.write("\t\t<section id=\"footer\">\n");
      out.write("           <h3>footer of the website </h3>\n");
      out.write("       </section>\n");
      out.write("    </body>\n");
      out.write("    \n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
