/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.47
 * Generated at: 2018-07-22 18:23:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import webProject.bean.*;
import webProject.daoImpl.*;
import webProject.service.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("webProject.service");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("webProject.bean");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("webProject.daoImpl");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--Final project-->\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    \r\n");
      out.write("    <title>Homeless Final Project</title>\r\n");
      out.write("    \r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("\t\t<script src=\"http://html5shiv.googlecode.com/svn/trunk/html5.js\"></script>\r\n");
      out.write("\t\t<![endif]-->\r\n");
      out.write("        <!--[if lte IE 9]> \r\n");
      out.write("\t    <script src=\"http://css3-mediaqueries-\tjs.googlecode.com/svn/trunk/css3-\tmediaqueries.js\"></script> \r\n");
      out.write("        <![endif]-->\r\n");
      out.write("         \r\n");
      out.write("    <link rel =\"stylesheet\" href=\"CSS/homeless.css\" type=\"text/css\">\r\n");
      out.write("    <link rel =\"stylesheet\" href=\"CSS/servicesStyle.css\" type=\"text/css\">\r\n");
      out.write("    <meta name=\"keywords\" content=\"homeless, welfare, charity, volunteer, homelessness\">\r\n");
      out.write("    <script>\r\n");
      out.write("\r\n");
      out.write("    function access(){ \r\n");
      out.write("        \t");
 
        		
        	
              if(request.getSession().getAttribute("msg")!=null){
      
            String str=request.getSession().getAttribute("msg").toString();
      out.write("           \r\n");
      out.write("            alert('notice'+\" : \"+\"");
      out.print(str);
      out.write("\");\r\n");
      out.write("            ");
  
             request.getSession().setAttribute("msg", null); }else {
      out.write("\r\n");
      out.write("           \r\n");
      out.write("            ");
}
      out.write("\r\n");
      out.write("            } \r\n");
      out.write("        </script>\r\n");
      out.write("    </head>\r\n");
      out.write("    \r\n");
      out.write("   <body onload=\"access()\" >\r\n");
      out.write("   ");
  try{
	   StartVolunteeringBean user = (StartVolunteeringBean)request.getSession().getAttribute("user");
        AbstractDao abd=new AbstractDao();
     String name=user.getFname();
       System.out.println("user"+user);
      
       
       
      out.write("\r\n");
      out.write("       <header class=\"mainpic\">\r\n");
      out.write("          <nav>\r\n");
      out.write("            <a href=\"home.jsp\">Home</a>\r\n");
      out.write("\t\t\t<a href=\"aboutus.jsp\">About Us</a>\r\n");
      out.write("            <a href=\"volunteers.jsp\">Volunteers</a>\r\n");
      out.write("            <a href=\"organisations.jsp\">Organisations</a>\r\n");
      out.write("            <a href=\"resources.jsp\">Resources</a>\r\n");
      out.write("            <a href=\"contactus.jsp\">Contact us</a>\r\n");
      out.write("            <a href=\"logoutServlet\">LogOut</a>\r\n");
      out.write("        </nav>    \r\n");
      out.write("       </header>\r\n");
      out.write("       \r\n");
      out.write("       <section class=\"features\">\r\n");
      out.write("           <h3 class=\"text-center\">Do you want to help with the homelessness crisis in Dublin? Do you know where you're going to sleep tonight?</h3>\r\n");
      out.write("           <p class=\"copy\">\r\n");
      out.write("           A place dedicated to homelessness in Dublin. We know that there are Dubliners who want to help with the homeless Crisis. This is how you can help. Volunteer your time. We can all play a part. We can all help to support those who are on the margins of society. We know that you understand and want to help. Here's where you can offer real support!!\r\n");
      out.write("           </p>\r\n");
      out.write("           \r\n");
      out.write("       </section>\r\n");
      out.write("\r\n");
      out.write("<section class=\"boxes\">\r\n");
      out.write("<div>\r\n");
      out.write("\t\t<div class=\"box-left\">\r\n");
      out.write("<h2 class=\"volunteer\">I want to volunteer</h2>\r\n");
      out.write("<ul>\r\n");
      out.write("<li>\r\n");
      out.write("<a href=\"\">Start Volunteering</a>\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"\">Find your local centre</a></li>\r\n");
      out.write("<li><a href=\"\">Learn about volunteering</a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("\t\t<div class=\"box-right\">\r\n");
      out.write("<h2 class=\"organisation\">I want to recruit volunteers</h2>\r\n");
      out.write("<ul>\r\n");
      out.write("<li><a href=\"\">Advertise a role</a></li>\r\n");
      out.write("<li><a href=\"\">Find your local centre</a></li>\r\n");
      out.write("<li><a href=\"\">Employee volunteering</a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("       </section><br/><br/><br/><br/><br/><br/><br/><br/><br/>\r\n");
      out.write(" \r\n");
      out.write("    \t ");

       
       
}catch(Exception e){
	String ipAddress = request.getHeader("X-FORWARDED-FOR");
	if (ipAddress == null) {
		   ipAddress = request.getRemoteAddr();
	}
	new controller().addLog("URLInjection", ipAddress);
	session.setAttribute("msg", "URLInjection detected");
	response.sendRedirect("login.jsp");
}

      out.write("\r\n");
      out.write("<br/><br/><br/><br/><br/><br/><br/><br/><br/>\r\n");
      out.write("\t<section id=\"footer\">\r\n");
      out.write("           <h3>footer of the website </h3>\r\n");
      out.write("       </section>\r\n");
      out.write("   </body>\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
