/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.47
 * Generated at: 2018-07-22 18:22:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import webProject.bean.*;
import webProject.daoImpl.*;
import webProject.service.*;
import java.util.*;

public final class startVolunteering_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("webProject.service");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("webProject.bean");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("webProject.daoImpl");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--Final project-->\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    \r\n");
      out.write("    <title>Homeless Final Project</title>\r\n");
      out.write("    \r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("\t\t<script src=\"http://html5shiv.googlecode.com/svn/trunk/html5.js\"></script>\r\n");
      out.write("\t\t<![endif]-->\r\n");
      out.write("        <!--[if lte IE 9]> \r\n");
      out.write("\t    <script src=\"http://css3-mediaqueries-\tjs.googlecode.com/svn/trunk/css3-\tmediaqueries.js\"></script> \r\n");
      out.write("        <![endif]-->\r\n");
      out.write("         \r\n");
      out.write("    <link rel =\"stylesheet\" href=\"CSS/homeless.css\" type=\"text/css\">\r\n");
      out.write("     <link rel =\"stylesheet\" href=\"CSS/style.css\" type=\"text/css\">\r\n");
      out.write("     <link rel =\"stylesheet\" href=\"CSS/servicesStyle.css\" type=\"text/css\">\r\n");
      out.write("    \r\n");
      out.write("   <meta name=\"keywords\" content=\"homeless, welfare, charity, volunteer, homelessness\">\r\n");
      out.write("  <script>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("    function access(){ \r\n");
      out.write("        \t");
         	
              if(request.getSession().getAttribute("msg")!=null){
      
            String str=request.getSession().getAttribute("msg").toString();
      out.write("           \r\n");
      out.write("            alert('notice'+\" : \"+\"");
      out.print(str);
      out.write("\");\r\n");
      out.write("            ");
  
             request.getSession().setAttribute("msg", null); }else {
      out.write("\r\n");
      out.write("          \r\n");
      out.write("            ");
}
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("    \r\n");
      out.write("    function changeVal() \r\n");
      out.write("    { \r\n");
      out.write(" \t  \r\n");
      out.write(" \t  var organisationName=document.forms[\"form\"][\"organisationName\"].value;\r\n");
      out.write(" \t  window.location.replace(\"AdvertiseRole.jsp?organisationName=\"+organisationName);\r\n");
      out.write(" \t     \r\n");
      out.write(" \t   \r\n");
      out.write("    } \r\n");
      out.write("    </script>\r\n");
      out.write(" </head>\r\n");
      out.write("<body onload=\"access()\">\r\n");
      out.write("    \r\n");
      out.write("       <header class=\"mainpic\">\r\n");
      out.write("          \r\n");
      out.write("           <div class = \"welcome\">\r\n");
      out.write("               <h1>Register</h1><br/>\r\n");
      out.write("              <font color=\"white\"><h2>I-VOL is the national searchable database of volunteering opportunities in Ireland and is owned, managed and administered by Volunteer Ireland and the network of Volunteer Centres and Volunteer Information Services in Ireland. \r\n");
      out.write("              Completing this form allows you to register your interest in volunteering opportunities that are listed online. When you have completed the form, and provided us with a valid e-mail address, you will receive a confirmation email, and instructions on how to begin your search for opportunities.\r\n");
      out.write("               You only need to fill in this form once.</h2></font>\r\n");
      out.write("            \r\n");
      out.write("               </div>\r\n");
      out.write("         </header>\r\n");
      out.write("                <div class=\"box\" style=\"background:#808080; color:black; text-color:black;padding-left:15px;margin-left:300px;float:left;width:50% ; height:1000px;margin-right:25px;margin-top:25px;margin-bottom:100px;\"> \r\n");
      out.write("               \t<form action=\"startVolunteeringServlet\" method=\"post\" id=\"form\">\r\n");
      out.write("               \t\r\n");
      out.write("      \t\t\t\t<h1>Register Now</h1>\r\n");
      out.write("      \t\t\t\t<table>\r\n");
      out.write("      \t\t\t\t<tr>\r\n");
      out.write("      \t\t\t\t\t<td>First Name:</td>\r\n");
      out.write("      \t\t\t\t\t<td><input type=\"text\" name=\"fname\" placeholder=\"Enter First Name\" required/></td>\r\n");
      out.write("      \t\t\t\t</tr>\r\n");
      out.write("      \t\t\t\t<tr>\r\n");
      out.write("      \t\t\t\t\t<td>Last Name:</td>\r\n");
      out.write("      \t\t\t\t\t<td><input type=\"text\" name=\"lname\" placeholder=\"Enter Last Name\" required/></td>\r\n");
      out.write("      \t\t\t\t</tr>\r\n");
      out.write("      \t\t\t\t<tr>\r\n");
      out.write("      \t\t\t\t\t<td>Street Address:</td>\r\n");
      out.write("      \t\t\t\t\t<td><textarea name=\"adddress\" placeholder=\"Enter Address..\" style=\"margin-left:80px;width:300px;\"></textarea></td>\r\n");
      out.write("      \t\t\t\t</tr>\r\n");
      out.write("      \t\t\t\t<tr>\r\n");
      out.write("      \t\t\t\t\t<td>Town/City:</td>\r\n");
      out.write("      \t\t\t\t\t<td><input type=\"text\" name=\"city\" placeholder=\"Enter City\" required/></td>\r\n");
      out.write("      \t\t\t\t</tr>\r\n");
      out.write("      \t\t\t\t<tr>\r\n");
      out.write("      \t\t\t\t\t<td>Country:</td>\r\n");
      out.write("      \t\t\t\t\t<td><input type=\"text\" name=\"country\"  placeholder=\"Enter Country\" required/></td>\r\n");
      out.write("      \t\t\t\t</tr>\r\n");
      out.write("      \t\t\t\t<tr>\r\n");
      out.write("      \t\t\t\t\t<td>Email:</td>\r\n");
      out.write("      \t\t\t\t\t<td><input type=\"text\" name=\"email\" placeholder=\"Enter Email\" required/></td>\r\n");
      out.write("      \t\t\t\t</tr>\r\n");
      out.write("      \t\t\t\t<tr>\r\n");
      out.write("      \t\t\t\t\t<td>Password:</td>\r\n");
      out.write("      \t\t\t\t\t<td><input type=\"password\" name=\"password\" placeholder=\"Enter Password\" required/></td>\r\n");
      out.write("      \t\t\t\t</tr>\r\n");
      out.write("      \t\t\t\t<tr>\r\n");
      out.write("      \t\t\t\t\t<td>Phone:</td>\r\n");
      out.write("      \t\t\t\t\t<td><input type=\"text\" name=\"mobile\" placeholder=\"Enter Mobile No\" required/></td>\r\n");
      out.write("      \t\t\t\t</tr>\r\n");
      out.write("      \t\t\t\t\r\n");
      out.write("      \t\t\t\t<tr>\r\n");
      out.write("      \t\t\t\t\t<td>Select Role:</td>\r\n");
      out.write("      \t\t\t\t\t<td>\r\n");
      out.write("      \t\t\t\t\t<select name=\"role\" style=\"margin-left:80px;width:340px;\">\r\n");
      out.write("      \t\t\t\t\t<option value=\"--Select Volunteer Role--\">--Select Volunteer Role--</option>\r\n");
      out.write("      \t\t\t\t\t");

      					List<DataInterface> ls=new AbstractDao().listByQuery("from AdvertiseRoleBean");
      					Iterator<DataInterface>it=ls.iterator();
      					while(it.hasNext())
      					{
      						AdvertiseRoleBean roleBean=(AdvertiseRoleBean)it.next();
      					
      					
      out.write("\r\n");
      out.write("      \t\t\t\t\t\t<option value=\"");
      out.print(roleBean.getRole() );
      out.write('"');
      out.write('>');
      out.print(roleBean.getRole() );
      out.write("</option>\r\n");
      out.write("      \t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("      \t\t\t\t\t</select>\r\n");
      out.write("      \t\t\t\r\n");
      out.write("      \t\t\t\t</tr>\r\n");
      out.write("      \t\t\t\t\t<tr>\r\n");
      out.write("        \t\t\t\t\t<td><button type=\"submit\" style=\"width:200px;\">Submit</button></td>\r\n");
      out.write("        \t\t\t\t\t<td><button type=\"reset\" style=\"width:200px;\">Cancel</button></td>\r\n");
      out.write("        \t\t\t\t</tr>\r\n");
      out.write("      \t\t\t\t\t\r\n");
      out.write("  \t\t\t\t    </table> \r\n");
      out.write("  \t\t\t\t    <p style=\"font-size:20px;\">You already have a membership?<a href=\"login.jsp\">Login</a></p>          \t\r\n");
      out.write("               \t</form><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>\r\n");
      out.write("               \r\n");
      out.write("                </div><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>        <section id=\"footer\">\r\n");
      out.write("           <h3>footer of the website </h3>\r\n");
      out.write("       </section>\r\n");
      out.write("       \r\n");
      out.write("   </body>\r\n");
      out.write("  </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
